# DO NOT TOUCH! - This is for migrating the config file format if necessary.
version: 1
# The plugin's locale to use. Corresponds to a file in SkyPlayTime/locale without the file extension.
locale: en_US
# This is how often data is saved to the database
save-interval-seconds: 900
# The maximum number of location snapshots to save per-player.
max-location-history-count: 512
# The maximum age in seconds to keep location snapshots for.
# If the timestamp of the location snapshot is older than this number of seconds, it will be removed.
max-location-age-seconds: 300.0
# Should the database be backed-up when any play time is reset?
backup-on-reset: true
# Should a snapshot of the leaderboard be saved when any play time is reset?
leaderboard-snapshot-on-reset: true
# The cutoff for when old backups should be removed.
backups-remove-older-than: 30d
# The cutoff for when old leaderboard snapshots should be removed.
leaderboard-remove-older-than: 90d
# These are settings that can be applied when a player is marked as AFK.
player-settings:
    # Should afk players be able to pick up items?
    afk-item-pickup: false
    # Should afk players be invulnerable?
    afk-invulnerable: true
    # Should afk players be marked as sleeping?
    afk-sleeping: true
reset-settings:
    # The time zone to use when calculating reset times.
    zone-id: "America/New_York"
    # The day of week to reset weekly play time on.
    day-of-week: SUNDAY
    # A number between and including 1-24.
    # Example: 3 would be 3 AM, 15 would be 3 PM.
    reset-hour: 10
# Do not modify. For internal use only to automatically reset play time.
last-reset-times:
    daily: 0
    weekly: 0
    monthly: 0
    yearly: 0